language: java
os:
  - osx
  - linux
osx_image: xcode9.3
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gradle  ; fi

install:
  - DIR=$PWD; (cd /tmp; gradle wrapper --gradle-version=5.2.1; mv .gradle gradle gradlew $DIR)

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew packageApplicationDmg ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -f build/packaged/main/bundles/OMERO.insight-* ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew build ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -f build/distributions/OMERO.imagej-* ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -f build/distributions/OMERO.insight-* ; fi

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: build/distributions/*
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: build/packaged/main/bundles/*
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
