jobs:
  include:
   - os: osx
     language: java
     osx_image: xcode9.3
     before_install:
       - brew update
       - brew install gradle
     install:
       - DIR=$PWD; (cd /tmp; gradle wrapper --gradle-version=5.2.1; mv .gradle gradle gradlew $DIR)
     script:
       - travis_retry ./gradlew packageApplicationDmg
       - if [[ -n "$TRAVIS_TAG" ]]; then travis_retry ./gradlew packageImporterApplicationDmg ; fi
       - test -f build/packaged/main/bundles/OMERO.insight-*
   - os: linux
     language: java
     install:
       - DIR=$PWD; (cd /tmp; gradle wrapper --gradle-version=5.2.1; mv .gradle gradle gradlew $DIR)
     script:
       - ./gradlew build
       - test -f build/libs/omero_ij*
       - test -f build/distributions/OMERO.insight-*
   - os: windows
     language: sh
     before_install:
       - choco install gradle
       - choco install jdk8
       - choco install innosetup --version=5.6.1
       - export PATH="/c/Program Files/Java/jdk1.8.0_211:/c/ProgramData/chocolatey/lib/gradle/tools:$PATH"
       - export PATH="/c/Program Files (x86)/Inno Setup 5:$PATH"
       - export JAVA_HOME="/c/Program Files/Java/jdk1.8.0_211"
       - export GRADLE_OPTS="-Dorg.gradle.daemon=false"
     install:
       - DIR=$PWD
       - rm -rf $HOME/.gradle
       - gradle wrapper --gradle-version=5.2.1
       - mv .gradle gradle gradlew $DIR
     script:
       - travis_retry ./gradlew packageApplicationExe
       - if [[ -n "$TRAVIS_TAG" ]]; then travis_retry ./gradlew packageImporterApplicationExe ; fi

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: build/libs/omero_*
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: build/distributions/OMERO*
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: build/packaged/main/bundles/*
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME != linux"
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: build/packaged/installImporterDist/bundles/*
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME != linux"
